language: python
python:
  - "2.7"

before_install:
  pip install codecov

install:

# run tests
script: nosetests --with-coverage

after_success:
  codecov --token=08889027-2a23-4998-ae8c-947be7612fa6

branches:
  only:
    - master